### ISSUE TITLE
GUI TODO

### ISSUE THREAD

**Issue by artonge** [nextcloud/backup#25]
# List of TODOs for the GUI

## Fixes

- [x] "Allow to create restoring points during week day" ==> "Allow to create full restoring points during week day"
- [x] Fix front end build in CI: https://github.com/nextcloud/backup/runs/3975954528?check_suite_focus=true

## Design

- [ ] Only display the latest full and partial backup with a way to reveal the all list
- [ ] Call with Jan/Maxence/Louis

**Comment by artonge** [comment]
Thanks for the input @nimishavijay, tell me what you think :slightly_smiling_face: 

> For the orange icons are we using the warning colour variable? If not we can use that and it might look more consistent

![Screenshot from 2021-11-02 21-01-23](https://user-images.githubusercontent.com/6653109/139943800-5c8d8e7b-753e-4e61-8fae-60b5333c48b7.png)

>  In "Create restoring points during..." is it possible to use a time picker? If it's not possible can we change the options to HH:MM format (eg. 16:00, 17:00, etc)? Right now it's not immediately clear that it's a time field

![Screenshot from 2021-11-02 21-01-29](https://user-images.githubusercontent.com/6653109/139943835-f213606c-d6df-4026-a680-b531a5208cf3.png)

**Comment by artonge** [comment]
>  Duplicate the External Storage selection form in a new settings chapter 'App Data', the idea is to be able to mount a remote filesystem as the appdata folder of the app: https://github.com/nextcloud/backup/blob/master/README.md#appdata-on-external-storage

@ArtificialOwl can you point me to the API I should use for that?

**Comment by ArtificialOwl** [comment]
> @ArtificialOwl can you point me to the API I should use for that?

https://github.com/nextcloud/backup/pull/32 !
